site_name: MKDocs NFL Deep Learning
site_author: Manuel Rinaldi
site_description: This site is a collection of notebooks and articles about Deep Learning applied to NFL data.
site_url: https://mrinaldi2.github.io/nfl-deep-learning/
nav:
  - Home: index.md
  - Test: page.md
  - Notebook: notebook.ipynb
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        name: Switch to dark mode
        icon: material/toggle-switch-off-outline
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        name: Switch to light mode
        icon: material/toggle-switch-outline

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/mrinaldi2"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 NFL Deep Learning <a href="https://github.com/mrinaldi2" target="_blank" rel="noopener">Manuel Rinaldi</a>

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter:
      execute: false